openapi: "3.0.1"
info:
  title: "EV-IoT-Kit API"
  description: "This is an API for cloud backend of EV-IoT-Kit project, part of my\
    \ Diploma thesis. Server side is running on AWS API Gateway. \n\n More about project\
    \ at\n[m4rtin195.github.io/EV-IoT-Kit/](https://m4rtin195.github.io/EV-IoT-Kit/)\
    \ \n\n Martin Timko, 2021"
  contact:
    email: "martin.timko195@gmail.com"
  version: "v3"
servers:
- url: "https://uilqy1jfsf.execute-api.eu-central-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/v3"
tags:
- name: "Sigfox"
  description: "Endpoints for Sigfox Backend."
  externalDocs:
    description: "Console"
    url: "https://backend.sigfox.com/"
- name: "WLAN"
  description: "Endpoints for direct vehicle connection."
- name: "Android"
  description: "Endpoints for Android client."
paths:
  /android/fcm-register:
    post:
      tags:
      - "Android"
      description: "Register the app instance to FCM updates."
      parameters:
      - name: "userId"
        in: "header"
        required: true
        schema:
          type: "string"
      - name: "User-Agent"
        in: "header"
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FcmRegistration"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "OK"
          content: {}
      security:
      - User-Authorizer: []
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
        \ and headers"
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
  /android/fcm-unregister:
    post:
      deprecated: true
      tags:
      - "Android"
      parameters:
      - name: "userId"
        in: "header"
        required: true
        schema:
          type: "string"
      - name: "User-Agent"
        in: "header"
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FcmRegistration"
        required: true
      responses:
        "400":
          description: "400 response"
          content: {}
        "401":
          description: "401 response"
          content: {}
        "200":
          description: "200 response"
          content: {}
      security:
      - User-Authorizer: []
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
        \ and headers"
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
  /android/range:
    get:
      tags:
      - "Android"
      description: "Get bulk of available statuses for requested vehicle, from requested\
        \ time range."
      parameters:
      - name: "userId"
        in: "header"
        required: true
        schema:
          type: "string"
      - name: "timeTo"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "timeFrom"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "vehicleId"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "User-Agent"
        in: "header"
        schema:
          type: "string"
      responses:
        "404":
          description: "Statuses for requested vehicleId were not found."
          content: {}
        "200":
          description: "OK"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "Vehicle Forbidden"
          content: {}
      security:
      - User-Authorizer: []
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:get-status-range/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /online:
    head:
      description: "Check if API is online."
      operationId: "headOnline"
      responses:
        "200":
          description: "Yes, online"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
  /test:
    post:
      description: "Used for testing."
      operationId: "postTest"
      responses:
        "200":
          description: "..."
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:api-authorizer/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /sigfox/uplink:
    post:
      tags:
      - "Sigfox"
      description: "For obtaining new data from Sigfox Backend."
      operationId: "postSigfoxUplink"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VehicleStatus"
        required: true
      responses:
        "400":
          description: "Parsing error"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "OK"
          content: {}
      security:
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
        \ and headers"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:status-receive/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
  /wlan:
    post:
      tags:
      - "WLAN"
      description: "For obtaining new data directly from the vehicle."
      parameters:
      - name: "connectivityMethod"
        in: "header"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VehicleStatus"
        required: true
      responses:
        "400":
          description: "Parsing error"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "OK"
          content: {}
      security:
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate body, query string parameters,\
        \ and headers"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:status-receive/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /sigfox/downlink:
    post:
      deprecated: true
      tags:
      - "Sigfox"
      operationId: "postSigfoxDownlink"
      responses:
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "200 response"
          content: {}
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
  /android/last:
    get:
      tags:
      - "Android"
      description: "Get last available status for requested vehicle."
      parameters:
      - name: "userId"
        in: "header"
        required: true
        schema:
          type: "string"
      - name: "vehicleId"
        in: "query"
        required: true
        schema:
          type: "string"
      - name: "User-Agent"
        in: "header"
        schema:
          type: "string"
      responses:
        "404":
          description: "Status for requested vehicleId was not found."
          content: {}
        "200":
          description: "OK"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "Vehicle Forbidden"
          content: {}
      security:
      - User-Authorizer: []
      - api_key: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:get-status-last/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
components:
  schemas:
    FcmRegistration:
      required:
      - "fcmToken"
      - "vehicleId"
      type: "object"
      properties:
        vehicleId:
          type: "string"
        fcmToken:
          type: "string"
        state:
          type: "boolean"
    VehicleStatus:
      required:
      - "id"
      - "vehicleId"
      type: "object"
      properties:
        id:
          type: "string"
        vehicleId:
          type: "string"
        timestamp:
          type: "integer"
          format: "int32"
        connectivity:
          type: "integer"
          format: "int32"
          enum:
          - -1
          - 0
          - 1
          - 2
        state:
          type: "integer"
          format: "int32"
          enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
        current_charge:
          type: "integer"
          format: "int32"
        target_charge:
          type: "integer"
          format: "int32"
        current:
          type: "integer"
          format: "int32"
        elapsed_time:
          type: "integer"
          format: "int32"
        remain_time:
          type: "integer"
          format: "int32"
        range:
          type: "integer"
          format: "int32"
        outdoor_temperature:
          type: "number"
        indoor_temperature:
          type: "number"
        location:
          type: "string"
        max_current:
          type: "integer"
          format: "int32"
        desired_temperature:
          type: "number"
  securitySchemes:
    User-Authorizer:
      type: "apiKey"
      name: "Unused"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
      x-amazon-apigateway-authorizer:
        type: "request"
        authorizerUri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:801154222515:function:api-authorizer/invocations"
        authorizerResultTtlInSeconds: 0
        identitySource: "method.request.header.userId, method.request.querystring.vehicleId"
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
x-amazon-apigateway-documentation:
  version: "1.0"
  createdDate: "2021-11-14T02:51:31Z"
  documentationParts:
  - location:
      type: "API"
    properties:
      info:
        description: "This is an API for cloud backend of EV-IoT-Kit project, part\
          \ of my Diploma thesis. Server side is running on AWS API Gateway. \n\n\
          \ More about project at\n[m4rtin195.github.io/EV-IoT-Kit/](https://m4rtin195.github.io/EV-IoT-Kit/)\
          \ \n\n Martin Timko, 2021"
        contact:
          email: "martin.timko195@gmail.com"
      tags:
      - name: "Sigfox"
        description: "Endpoints for Sigfox Backend."
        externalDocs:
          description: "Console"
          url: "https://backend.sigfox.com/"
      - name: "WLAN"
        description: "Endpoints for direct vehicle connection."
      - name: "Android"
        description: "Endpoints for Android client."
  - location:
      type: "METHOD"
      path: "/android/fcm-register"
      method: "POST"
    properties:
      tags:
      - "Android"
      description: "Register the app instance to FCM updates."
  - location:
      type: "METHOD"
      path: "/android/fcm-unregister"
      method: "POST"
    properties:
      tags:
      - "Android"
  - location:
      type: "METHOD"
      path: "/android/last"
      method: "GET"
    properties:
      tags:
      - "Android"
      description: "Get last available status for requested vehicle."
  - location:
      type: "METHOD"
      path: "/android/range"
      method: "GET"
    properties:
      tags:
      - "Android"
      description: "Get bulk of available statuses for requested vehicle, from requested\
        \ time range."
  - location:
      type: "METHOD"
      path: "/online"
      method: "HEAD"
    properties:
      description: "Check if API is online."
  - location:
      type: "METHOD"
      path: "/sigfox/downlink"
      method: "POST"
    properties:
      tags:
      - "Sigfox"
  - location:
      type: "METHOD"
      path: "/sigfox/uplink"
      method: "POST"
    properties:
      tags:
      - "Sigfox"
      description: "For obtaining new data from Sigfox Backend."
  - location:
      type: "METHOD"
      path: "/test"
      method: "POST"
    properties:
      description: "Used for testing."
  - location:
      type: "METHOD"
      path: "/wlan"
      method: "POST"
    properties:
      tags:
      - "WLAN"
      description: "For obtaining new data directly from the vehicle."
  - location:
      type: "RESPONSE"
      method: "GET"
      statusCode: "200"
    properties:
      description: "200 response"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-register"
      method: "POST"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-register"
      method: "POST"
      statusCode: "400"
    properties:
      description: "400 response"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-register"
      method: "POST"
      statusCode: "401"
    properties:
      description: "Unauthorized"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-unregister"
      method: "POST"
      statusCode: "200"
    properties:
      description: "200 response"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-unregister"
      method: "POST"
      statusCode: "400"
    properties:
      description: "400 response"
  - location:
      type: "RESPONSE"
      path: "/android/fcm-unregister"
      method: "POST"
      statusCode: "401"
    properties:
      description: "401 response"
  - location:
      type: "RESPONSE"
      path: "/android/last"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/android/last"
      method: "GET"
      statusCode: "401"
    properties:
      description: "Unauthorized"
  - location:
      type: "RESPONSE"
      path: "/android/last"
      method: "GET"
      statusCode: "403"
    properties:
      description: "Vehicle Forbidden"
  - location:
      type: "RESPONSE"
      path: "/android/last"
      method: "GET"
      statusCode: "404"
    properties:
      description: "Status for requested vehicleId was not found."
  - location:
      type: "RESPONSE"
      path: "/android/range"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/android/range"
      method: "GET"
      statusCode: "401"
    properties:
      description: "Unauthorized"
  - location:
      type: "RESPONSE"
      path: "/android/range"
      method: "GET"
      statusCode: "403"
    properties:
      description: "Vehicle Forbidden"
  - location:
      type: "RESPONSE"
      path: "/android/range"
      method: "GET"
      statusCode: "404"
    properties:
      description: "Statuses for requested vehicleId were not found."
  - location:
      type: "RESPONSE"
      path: "/online"
      method: "HEAD"
      statusCode: "200"
    properties:
      description: "Yes, online"
  - location:
      type: "RESPONSE"
      path: "/sigfox/downlink"
      method: "POST"
      statusCode: "200"
    properties:
      description: "200 response"
  - location:
      type: "RESPONSE"
      path: "/sigfox/downlink"
      method: "POST"
      statusCode: "401"
    properties:
      description: "Unauthorized"
  - location:
      type: "RESPONSE"
      path: "/sigfox/uplink"
      method: "POST"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/sigfox/uplink"
      method: "POST"
      statusCode: "400"
    properties:
      description: "Parsing error"
  - location:
      type: "RESPONSE"
      path: "/sigfox/uplink"
      method: "POST"
      statusCode: "401"
    properties:
      description: "Unauthorized"
  - location:
      type: "RESPONSE"
      path: "/test"
      method: "POST"
      statusCode: "200"
    properties:
      description: "..."
  - location:
      type: "RESPONSE"
      path: "/wlan"
      method: "POST"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/wlan"
      method: "POST"
      statusCode: "400"
    properties:
      description: "Parsing error"
  - location:
      type: "RESPONSE"
      path: "/wlan"
      method: "POST"
      statusCode: "401"
    properties:
      description: "Unauthorized"
x-amazon-apigateway-request-validators:
  Validate body, query string parameters, and headers:
    validateRequestParameters: true
    validateRequestBody: true
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false